spring.application.name=product-service
spring.main.banner-mode=off
server.port=8080
##Kafka related properties##
kafka-config.producer.bootstrap-servers=localhost:9092
kafka-config.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka-config.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
kafka-config.producer.acks=all
#kafka-config.producer.retries=10
#kafka-config.producer.retry-backoff-ms=10000
kafka-config.producer.delivery-timeout-ms=120000
kafka-config.producer.linger-ms=0
kafka-config.producer.request-timeout-ms=30000
kafka-config.producer.idempotence=true
kafka-config.producer.max-in-flight-request-per-connection=5
kafka-config.topic.product-created=product-created-events-topic
