spring.application.name=product-service
spring.main.banner-mode=off
server.port=8080
##Kafka related properties##
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kakfa.producer.acks=all
product.kafka.topic.product-created=product-created-events-topic

