spring.application.name=email-notification-service
server.port=8081
kafka-config.consumer.bootstrap-servers=localhost:9092
kafka-config.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka-config.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
kafka-config.consumer.group-id=product-created-events
kafka-config.consumer.trusted-packages=com.epam.events.model